version: "3"
services:
  app:
    container_name: "bayview-development"
    build:
      context: .
      target: dev
    networks:
      - app_network
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

networks:
  app_network:
    driver: bridge
